#!/bin/sh

waitron wm_config border_width 1
waitron wm_config color_focused 0xfabd2f
waitron wm_config color_unfocused 0x282828
waitron wm_config gap_width all 20
waitron wm_config gap_width top 50
waitron wm_config grid_gap_width 20
waitron wm_config cursor_position bottom_right
waitron wm_config groups_nr 4
waitron wm_config enable_sloppy_focus true
